apiVersion: apps/v1
kind: Deployment
metadata:
  name: std-app
spec:
  replicas: 4
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: c1
          image: abhiprayadh/studentapp:v1
          ports:
            - containerPort: 80
