apiVersion: v1
kind: ReplicationController
metadata:
  name: vc-game
spec:
  replicas: 4
  selector:
    env: dev
  template:
    metadata:
      name: tmp-game
      labels:
        env: dev
    spec:
      containers:
        - name: c1
          image: abhinagare/abhi-new-repo:v2
          ports:
            - containerPort: 80
